[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from   = "https://www.canadianroofers.ca/*"
  to     = "https://canadianroofers.ca/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "http://www.canadianroofers.ca/*"
  to     = "https://canadianroofers.ca/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "http://canadianroofers.ca/*"
  to     = "https://canadianroofers.ca/:splat"
  status = 301
  force  = true
